### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by calikevuche** [infectiouscontentengineering/typescript-openai-api-testing#1]
Ensure you have error handling or a retry mechanism in your request handler to manage cases when the API returns errors. I'll add some code in the repo.

**Comment by infectiouscontentengineering** [comment]
Thanks good sir.

There is error handling now. Please feel free to add.

I will start a new repo that integrates RAG next.

**Comment by infectiouscontentengineering** [comment]
Closing for now.
